### ISSUE TITLE
Won't compile

### ISSUE THREAD

**Issue by sheffieldnikki** [technoblogy/tiny-i2c#1]
Various things aren't defined (PIN_USI_SCL, DDR_USI, etc) as the code stands, so it doesn't compile.

Does TinyI2CMaster.cpp need something like #include "usi_io.h" added at the top?

**Comment by DirtyEngineer** [comment]
Have you tried adding

```
int const sda = 0;
int const scl = 2;
```

To your sketch?

Also be sure that you are using Spence Konde [ATTinyCore](https://github.com/SpenceKonde/ATTinyCore) or you will have issues compiling.

**Comment by sheffieldnikki** [comment]
Thanks, it was indeed that I was using damellis/attiny instead of SpenceKonde/ATTinyCore. Could a note be added in the README or top of TinyI2CMaster.cpp to that effect?
