### ISSUE TITLE
Decluttering the signal

### ISSUE THREAD

**Issue by oomek** [technoblogy/tiny-i2c#12]
Is it possible to tidy up the signal a little bit? I've been comapring the output of your lib with what the mcu of my TV is outputting and I've noticed some abnormalities: the unneccessary SDA spikes and the delay betwen the data and the ACK bit. Is it doable, or it's some hardware limitation?

![image](https://user-images.githubusercontent.com/2974860/80652043-08b05c00-8a6f-11ea-9b66-9a8b665dd9f4.png)

**Comment by technoblogy** [comment]
The ATtiny85 doesn't have a dedicated I2C peripheral, and my routines use the general-purpose USI peripheral to emulate I2C. It's possible the emulation isn't perfect. Is this causing you a problem? You could try adjusting the delays in the code; they are inserted by the macros DELAY_T2TWI and DELAY_T4TWI.

**Comment by oomek** [comment]
I was experimenting with delays few days ago, but it did not have any effect on those spikes except making them wider.

**Comment by technoblogy** [comment]
Are these problems stopping it working for you?
