### ISSUE TITLE
ATTiny13a

### ISSUE THREAD

**Issue by montyx99** [technoblogy/tiny-i2c#9]
Hello,
I tried to compile this awesome library to an ATTiny13a without luck.
Is there any possibility to support the https://github.com/MCUdude/MicroCore library in the near future?

Thanks in advance

**Comment by technoblogy** [comment]
Sorry, as far as I know it doesn't have a USI so there's no way of supporting it.

**Comment by montyx99** [comment]
Thanks for the quick answer, you are right. During this time I've found this great comparison chart on wiki:
https://en.wikipedia.org/wiki/ATtiny_microcontroller_comparison_chart
So I've ordered some ATTiny85 quickly :joy:
